import { BlogByTitle } from "@/components/Blog/Blog";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { BlogByTitle as BlogByTitleProp } from "@/types/blog";
import Head from "next/head";

export default function Blog() {
  const blog: BlogByTitleProp = {
    id: "1",
    title: "What do you want to know about UI",
    author: "Tom Hank",
    position: "Creative Director",
    coverImage: "offerings-2.png",
    authorImage: "author.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium, alias nam? Tempore",
    youMayLike: [
      {
        id: "1",
        title: "All the features you want to know",
        description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis fugit dolorum amet dolores praesentium, alias nam? Tempore",
      },
    ],
  };
  return (
    <main className="bg-blue-100">
      <Head>
        <title>ViruCut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Header />
      <section className="min-h-screen">
        <BlogByTitle {...blog} />
      </section>
      <Footer />
    </main>
  );
}
