"use client";
import Head from "next/head";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import ContactUsFormWithMap from "@/components/Contactus/Contactus";
import { AboutUsPage } from "@/components/About/About";
import Employees from "@/components/Employees/employees";
/**
 * AboutUs component is the main component for the About Us page.
 * It renders a Hero section, an About Us section and a Contact Us Form with Map.
 * The Hero section has a background image and a button to learn more.
 * The About Us section has a title, a paragraph of text and an image.
 * The Contact Us Form with Map section has a contact form and a map.
 */
export default function AboutUs() {
  return (
    <main>
      <Head>
        <title>ViruCut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Header />
      <AboutUsPage />
      <Employees />
      <ContactUsFormWithMap />
      <Footer />
    </main>
  );
}
