import Head from "next/head";

export default function AboutUs() {
  return (
    <main>
      <Head>
        <title>ViruCut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <div className="flex lg:flex-row md:flex-row flex-col items-center justify-center gap-1 m-1 ">
        <div className="bg-blue-500 sm:bg-red-500 h-40 w-32"></div>
        <div className="bg-red-400 h-40 w-32 sm:bg-blue-500"></div>
        <div className="bg-red-300 h-40 w-32"></div>
        <div className="hidden sm:block bg-green-500 h-10 w-10"></div>
      </div>
    </main>
  );
}
