import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import ProductsHero from "@/components/Products/products";
import { ProductsWCategory } from "@/components/ProductView/productView";
// import ProductSingleView from "@/components/ProductView/productView";
import Head from "next/head";

export default function SingleProductView() {
  return (
    <main>
      <Head>
        <title>ViruCut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Header />
      {/* <ProductSingleView /> */}
      <ProductsHero
        imgUrl="" //"https://images.unsplash.com/photo-1604014237800-1c9102c219da?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80"
        className=""
      />
      <ProductsWCategory
        products={[
          {
            name: "HRC67- for Harden Steel",
            series: "Golden Panda Series",
            image: "/images/products-1.jpg",
          },
          {
            name: "HRC67- for Harden Steel",
            series: "Golden Panda Series",
            image: "/images/products-1.jpg",
          },
          {
            name: "HRC67- for Harden Steel",
            series: "Golden Panda Series",
            image: "/images/products-1.jpg",
          },
          {
            name: "HRC67- for Harden Steel",
            series: "Golden Panda Series",
            image: "/images/products-1.jpg",
          },
          {
            name: "HRC67- for Harden Steel",
            series: "Golden Panda Series",
            image: "/images/products-1.jpg",
          },
          {
            name: "HRC67- for Harden Steel",
            series: "Golden Panda Series",
            image: "/images/products-1.jpg",
          },
          {
            name: "HRC67- for Harden Steel",
            series: "Golden Panda Series",
            image: "/images/products-1.jpg",
          },
          {
            name: "HRC68- for High Temprature Alloy",
            series: "Golden Panda Series",
            image: "/images/products-1.jpg",
          },
          {
            name: "HRC68- for High Temprature Alloy",
            series: "Golden Panda Series",
            image: "/images/products-1.jpg",
          },
        ]}
      />
      <Footer />
    </main>
  );
}
